### ISSUE TITLE
the evaluation results of monovit on driving stereo dataset

### ISSUE THREAD

**Issue by RuijieZhu94** [kieran514/robustdepth#1]
Thanks for open-sourcing your code. We used the official weights of monovit and robustdepth to test on the driving stereo dataset, and the results were quite different from those reported in the paper. What is the reason?

**Comment by RuijieZhu94** [comment]
It seems that the difference is caused by using images of different sizes.

**Comment by kieran514** [comment]
Hello, and thank you for your interest in our work. 

We use the full-size image and depth data from each weather condition as found on the DrivingStereo website [DrivingStereo](https://drivingstereo-dataset.github.io/). 

Initially, we reached out to the authors of MonoVit to see the exact process of evaluation they used; however, we received limited guidance. Therefore, using our evaluation script, we fairly test each method (using pretrained weights). This exact process should be fully reproducible, and the steps for evaluating out-of-distribution datasets are coming in the next few weeks.

**Comment by RuijieZhu94** [comment]
Thanks for your reply, we tested it on full-size images and got a result similar to the paper.
