### ISSUE TITLE
For ease of use, I have provided the particle files (in the required order) which should be extracted in /rain-rendering/data/particles/ found here.

### ISSUE THREAD

**Issue by Harbinzzy** [kieran514/robustdepth#10]
found here  This link won't work

**Comment by Harbinzzy** [comment]
https://drive.google.com/file/d/1Dkle1mFBUR2qKfamxoWZE88FoHmcUyzC/view?usp=sharing This link doesn't work. Thank you.

**Comment by kieran514** [comment]
Hello, this should now be fixed. Please look back at the read me https://drive.google.com/file/d/1h3P_-g-vgJmnt7IkDlM7xjuN6MAqvCDX/view?usp=sharing

**Comment by Harbinzzy** [comment]
Thank you
