### ISSUE TITLE
RainGan link not working?

### ISSUE THREAD

**Issue by shreyas-kamath-simplisafe** [kieran514/robustdepth#3]
Hi, 

I was looking at using the RainGan as mentioned in the repo. But I think the link is broken. Can you please help?

Thank you,
Best,
Shreyas Kamath

**Comment by kieran514** [comment]
Hello Shreyas, 

I appreciate your interest in our work and many thanks for pointing this out. The links have been updated, and everything should be accessible now.

Best wishes,
Kieran Saunders
