### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by alvariseppanen** [kieran514/robustdepth#4]
Hello,
 
I was wondering if you could provide the augmented images, so I don't have to run those ~20h scripts.

Looking forward to your reply!

**Comment by kieran514** [comment]
Hello, thank you for expressing interest in our paper.

Given the substantial size of the augmented dataset, direct sharing isn't currently possible.

As an alternative, I've provided the test data. This will allow you to run all evaluation scripts without the necessity of generating the data.
