### ISSUE TITLE
questions about the nuScenes results

### ISSUE THREAD

**Issue by Alex-Wula** [kieran514/robustdepth#6]
Dear authors:
Thanks for your work! Your work helps me a lot. Could you please show the results of your model under the day-clear and day-rain conditions like the results you show in Table 5 in your paper ? I would be grateful if you could offer the results! Thanks a lot!

**Comment by kieran514** [comment]
Hello, thank you for your interest in our work. If I understand your question correctly, you wish to use the NuScenes dataset for evaluation during both day and rain times. Unfortunately, the script to create the splits for NuScenes has been lost. To create the NuScenes night test set, we simply downloaded the entire NuScenes dataset and searched for descriptions of nighttime images. Then, we created a test split of this data along with its corresponding LiDAR data.

I hope this helps. For further guidance, please refer to how we evaluate using NuScenes data at night.
