### ISSUE TITLE
Wrong loader

### ISSUE THREAD

**Issue by wangjiyuan9** [kieran514/robustdepth#8]
Hi, thank you for your amazing work. I found your code always uses image_02 even if the side is 'r':
https://github.com/kieran514/robustdepth/blob/8d96d0e6dc3c69bcf21a211bb0c4414304dded96/Robust-Depth/datasets/kitti_dataset.py#L73-L83

**Comment by kieran514** [comment]
Hello, thank you for your interest in our paper.

Our code only generates augmented versions of the left side of the images. Originally, it was designed to use both sides, but we choose to focus solely on the left side for the sake of simplifying augmentation creation. It's worth noting that this choice results in images being repeated, considering both left and right sides. However, this aligns with the number of images used per epoch in comparison to other methods.

One could argue that this approach leads to less unique data being processed by our method, potentially resulting in improved performance if both sides were used, particularly if right-side augmentations are created. Therefore, for best practice, we should consider incorporating right-side augmentations if they are created, as this may offer opportunities for future enhancements.

But this is a very valid point!
